#spring.profiles.active: ${SPRING_PROFILES_ACTIVE:native}

spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
    include: native
  rabbitmq:
    host: ${RABBITMQ_SERVICE_SERVICE_HOST:rabbitmq}
    port: ${RABBITMQ_SERVICE_SERVICE_PORT:5672}
    username: ${RABBITMQ_SERVICE_USER:guest}
    password: ${RABBITMQ_SERVICE_PASSWORD:guest}

server:
  port: 8888

security:
  user:
    password: ${CONFIG_SERVICE_PASSWORD:123456}

---
spring.profiles: k8s
spring.profiles.include: subversion

spring:
  cloud:
    config:
      server:
        svn:
          uri: ${CONFIG_SERVICE_SVN_URI}
          username: ${CONFIG_SERVICE_SVN_USER}
          password: ${CONFIG_SERVICE_SVN_PWD}

---
spring.profiles: docker
spring.profiles.include: native

spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:///var/lib/config-repo