spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
     active: native

server:
  port: 8888

security:
  user:
    password: ${CONFIG_SERVICE_PASSWORD:123456}

---
spring:
  profiles:
    include: native
    active: docker
  cloud:
    config:
      server:
        native:
          search-locations: file:///var/lib/config-repo

---
spring:
  profiles:
    active: k8s
    include: subversion
  cloud:
    config:
      server:
        svn:
          uri: ${CONFIG_SERVICE_SVN_URI}
          username: ${CONFIG_SERVICE_SVN_USER}
          password: ${CONFIG_SERVICE_SVN_PWD}