debug: false

logging:
  level:
    org.springframework.security: DEBUG
    com.netflix:
      eureka: OFF
      discovery: OFF
  pattern:
    level: "%clr(%5p) %clr([${spring.application.name:},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]){yellow}"
#    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([trace=%X{X-B3-TraceId:-},span=%X{X-B3-SpanId:-}]){yellow} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wex"

info:
  component: ${spring.application.name}
  id: ${instanceId:unknown}

endpoints.shutdown.enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${REGISTRY_SERVICE_HOST:registry}:${REGISTRY_SERVICE_PORT:8761}/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://${AUTH_SERVICE_SERVICE_HOST:auth-service}:${AUTH_SERVICE_SERVICE_PORT:5000}/uaa/users/current

spring:
  rabbitmq:
    host: ${RABBITMQ_SERVICE_SERVICE_HOST:rabbitmq}
    port: ${RABBITMQ_SERVICE_SERVICE_PORT:5672}
    username: ${RABBITMQ_SERVICE_USER:guest}
    password: ${RABBITMQ_SERVICE_PASSWORD:guest}
  sleuth:
    log.json.enabled: true