spring:
  data:
    mongodb:
      host: ${MONGODB_SERVICE_HOST:auth-mongodb}
      username: user
      password: ${MONGODB_PASSWORD}
      database: piggymetrics
      port: ${MONGODB_SERVICE_PORT:27017}
  sleuth:
    scheduled:
      enabled: false
    sampler:
      percentage: 1
      
server:
  context-path: /uaa
  port: 5000
