spring:
  datasource:
    schema: classpath:/mysql.sql
    url: jdbc:mysql://${MYSQL_MASTER_SERVICE_HOST:monitoring-zipkin-mysql}/zipkin
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
    initialize: true
    continueOnError: true
  sleuth:
    enabled: false

zipkin:
  storage:
    type: mysql