security:
  oauth2:
    client:
      clientId: notification-service
      clientSecret: ${NOTIFICATION_SERVICE_PASSWORD}
      accessTokenUri: http://${AUTH_SERVICE_SERVICE_HOST:auth-service}:${AUTH_SERVICE_SERVICE_PORT:5000}/uaa/oauth/token
      grant-type: client_credentials
      scope: server

server:
  context-path: /notifications
  port: 8000

remind:
  cron: 0 0 0 * * *
  email:
    text: "Hey, {0}! We''ve missed you here on PiggyMetrics. It''s time to check your budget statistics.\r\n\r\nCheers,\r\nPiggyMetrics team"
    subject: PiggyMetrics reminder

backup:
  cron: 0 0 12 * * *
  email:
    text: "Howdy, {0}. Your account backup is ready.\r\n\r\nCheers,\r\nPiggyMetrics team"
    subject: PiggyMetrics account backup
    attachment: backup.json

spring:
  data:
    mongodb:
      host: ${MONGODB_SERVICE_HOST:notification-mongodb}
      username: user
      password: ${MONGODB_PASSWORD}
      database: piggymetrics
      port: ${MONGODB_SERVICE_PORT:27017}
  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:465}
    username: ${SMTP_USER:dev-user}
    password: ${SMTP_PASSWORD:dev-password}
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          ssl:
            enable: ${SMTP_SSL_ENABLE:true}
  sleuth:
    scheduled:
      enabled: false
    sampler:
      percentage: 1
