security:
  oauth2:
    client:
      clientId: statistics-service
      clientSecret: ${STATISTICS_SERVICE_PASSWORD}
      accessTokenUri: http://${AUTH_SERVICE_SERVICE_HOST:auth-service}:${AUTH_SERVICE_SERVICE_PORT:5000}/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: ${MONGODB_SERVICE_HOST:statistics-mongodb}
      username: user
      password: ${MONGODB_PASSWORD}
      database: piggymetrics
      port: ${MONGODB_SERVICE_PORT:27017}

  sleuth:
    sampler:
      percentage: 1

server:
  context-path: /statistics
  port: 7000

rates:
  url: http://api.fixer.io